/** @type {import('tailwindcss').Config} */
import withMT from "@material-tailwind/react/utils/withMT";

export default withMT({
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        Nunito: ["CustomFont", "system-ui", "sans"],
        AnandaBlackPersonalUseRegular: [
          "AnandaBlackPersonalUseRegular",
          "sans-serif",
        ],
        AspireDemibold: ["AspireDemibold", "sans-serif"],
        AutumnFlowers: ["AutumnFlowers", "sans-serif"],
        Calligrapher: ["Calligrapher", "sans-serif"],
        ChicanosPersonalUseRegular: [
          "ChicanosPersonalUseRegular",
          "sans-serif",
        ],
        DoveOfPeacePersonalUse: ["DoveOfPeacePersonalUse", "sans-serif"],
        EmotionalRescuePersonalUseRegular: [
          "EmotionalRescuePersonalUseRegular",
          "sans-serif",
        ],
        FeelfreePersonalUseRegular: [
          "FeelfreePersonalUseRegular",
          "sans-serif",
        ],
        GeraldinePersonalUseItalic: [
          "GeraldinePersonalUseItalic",
          "sans-serif",
        ],
        IndentureEnglishPenmanDemo: [
          "IndentureEnglishPenmanDemo",
          "sans-serif",
        ],
        LambencyRegular: ["LambencyRegular", "sans-serif"],
        MutalisFashionPersonalUseRegular: [
          "MutalisFashionPersonalUseRegular",
          "sans-serif",
        ],
        NatureBeautyPersonalUse: ["NatureBeautyPersonalUse", "sans-serif"],
        SellenaBrush: ["SellenaBrush", "sans-serif"],
        StylishCalligraphyDemo: ["StylishCalligraphyDemo", "sans-serif"],
        SweetHipster: ["SweetHipster", "sans-serif"],
        TheCheese: ["TheCheese", "sans-serif"],
        WeddingdayPersonalUseRegular: [
          "WeddingdayPersonalUseRegular",
          "sans-serif",
        ],
        adorabelle: ["AdorabelleFreePersonalUseRg", "sans"],
        amandez: ["Amandez TTF Personal", "sans"],
        baletta: ["Baletta", "sans"],
        "beautiful-people": ["BeautifulPeoplePersonalUse", "sans"],
        bulgathi: ["Bulgathi", "sans"],
        calisshascript: ["CalisshascriptRegular", "sans"],
        "christmas-calligraphy": ["ChristmasCalligraphyPersonal", "sans"],
        dharma: ["Dharma", "sans"],
        "drama-queen": ["DramaQueenFreePersonalUseS", "sans"],
        flicker: ["Flicker", "sans"],
        goldyear: ["GoldyearpersonalUseRegular", "sans"],
        haniya: ["HaniyaFreeTrial", "sans"],
        haydena: ["Haydena", "sans"],
        kagok: ["Kagokpersonal", "sans"],
        kameliascript: ["KameliascriptRegular", "sans"],
        kastela: ["Kastela", "sans"],
        krinah: ["Krinahpersonal", "sans"],
        "lemon-jelly": ["LemonJellyPersonalUse", "sans"],
        "love-seed": ["LoveSeed", "sans"],
        matchalatte: ["Matchalatte", "sans"],
        muthiara: ["MuthiaraDemoVersion", "sans"],
        qiuba: ["QIUBApersonal", "sans"],
        rengkox: ["Rengkoxpersonal", "sans"],
        "risalah-cinta": ["RisalahCinta", "sans"],
        roback: ["ROBACKpersonal", "sans"],
        rostina: ["Rostina", "sans"],
        shawty: ["ShawtyRegular", "sans"],
        "shogeking-oniki": ["ShogekingOniki", "sans"],
        silentha: ["Silentha", "sans"],
        sketsaramadhan: ["Sketsaramadhan", "sans"],
        "spooky-zombie": ["SpookyZombie", "sans"],
        "spring-season": ["SpringSeasonPersonalUseRegular", "sans"],
        wushin: ["WUSHINpersonaluse", "sans"],
      },
    },
  },
  plugins: [],
});
